services:
  spring:
    container_name: training
    build:
      context: ./
      dockerfile: Dockerfile
    restart: "no"
    ports:
      - "8080:8080"
      - "5005:5005"
    env_file:
      - .env
    depends_on:
      - db
    links:
      - db

  db:
    container_name: training-db
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - db_logs:/var/log/mysql
      - ./mysql/conf.d:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    env_file:
      - .env

volumes:
  db_data:
  db_logs:
