services:
  spring:
    container_name: training
    build:
      context: ./
      dockerfile: Dockerfile
    restart: "no"
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db
    links:
      - db

  db:
    container_name: training-db
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - ./.data/mysql:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql
    command:
      - "--lower_case_table_names=1"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    env_file:
      - .env

volumes:
  db:
    driver: local
    name: ${PROJECT_NAME}mysql_volume
